volumes:
  database:
    drive: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: /home/loumouli/data

services:
  nginx:
    build: ./srcs/nginx
    volumes:
      - database:/home/loumouli/data
    restart: always

