volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/loumouli/data/db
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/loumouli/data/mariadb

services:
  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress
    volumes:
      - db:/var/www/html
    networks:
      - network
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./srcs/nginx
    volumes:
      - db:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    restart: always


networks:
  network:
    name: network
    driver: bridge
